version: '3.8'

services:
    enb_mono_fdd:
        image: oai-enb:develop
        privileged: true
        container_name: prod-enb-mono-fdd
        environment:
            USE_FDD_MONO: 'yes'
            USE_B2XX: 'yes'
            USE_VOLUMED_CONF: 'yes'
            USE_ADDITIONAL_OPTIONS: --RUs.[0].max_rxgain 115 --RUs.[0].max_pdschReferenceSignalPower -27 --eNBs.[0].component_carriers.[0].pucch_p0_Nominal -96 --log_config.global_log_options level,nocolor,time
        volumes:
          - ./fr1_enb_mono_fdd_tim.conf:/opt/oai-enb/etc/mounted.conf
        networks:
            public_net:
                ipv4_address: 192.168.61.30
        healthcheck:
            # pgrep does NOT work
            test: /bin/bash -c "ps aux | grep -v grep | grep -c softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public_net:
        name: prod-oai-public-net
        ipam:
            config:
                - subnet: 192.168.61.0/26

